FragrantFlowers - Fertility settings fix
pether-pg/ONI_Mods_byPether pull request #80
Opened 2024-05-31 15:57 UTC by realwiseserpent

Hi! Just a small fix for fertility setting to support values less than 10%.

2024-06-10 19:56 UTC, pether-pg requested changes

2024-06-10 19:56 UTC, pether-pg commented on FragrantFlowers/Settings.cs
> +                CritterFertilityBonus = 0.5f;
no need to change default value

2024-06-11 14:24 UTC, realwiseserpent commented on FragrantFlowers/Settings.cs
> +                CritterFertilityBonus = 0.5f;
To my mind, 10% is quite a lot but ok.

2024-06-12 14:36 UTC, realwiseserpent commented on FragrantFlowers/Settings.cs
> +                CritterFertilityBonus = 0.5f;
Fixed.

2024-06-13 21:52 UTC, pether-pg approved these changes

2024-06-13 21:52 UTC, merged